### ISSUE TITLE
CDMX-AMG-MTY

### ISSUE THREAD

**Issue by edgaregurrola** [Observatorio-Ciudades/calidad-aire#6]
Download historical data from AMG, CDMX and MTY to create a beta analysis for this project.

**Comment by nateraluis** [comment]
Ya revise las gráficas, se ve interesante y se alcanza a ver un bajón en cierto momento. El rango de tiempo es por día o puede haber varias mediciones en un sólo día? Si hay varias podríamos calcular el promedio diario para que no tenga tanto ruido la gráfica no?

**Comment by edgaregurrola** [comment]
Hola, van varios puntos:

- Voy viendo que la regué con el issue, era el #2

- Con ese análisis lo primero que hice fue calcular la mediana para los valores de la calidad del aire de la Ciudad de México (que tenemos por estación y con concentración horaria y por estación) para que solo quedara un valor por día, como está en los datos del Air Quality Index Project (AQIP).

- Después tomé los valores de las ciudades mexicanas del AQIP y como los valores venían en índices los convertí a concentraciones. Ahí me di cuenta que los valores no estaban por día, se brincaban algunos (por ejemplo 2 días sí habían datos, 1 no, 1 día sí, 2 no, etc.)

- Hice un merge de los datos del AQIP y la CDMX para el mismo periodo y les apliqué una prueba estadística (prueba de t) que analiza si las diferencias entre los valores se pueden explicar por la aleatoriedad de la distribución en los valores o si efectivamente son estadísticamente diferentes. Con esta prueba me salió que todos eran distinos menos PM10. Esas son las gráficas comparativas entre CDMX y AQIP que dicen x1.

- Revisando las gráficas se ve que la tendencia es la misma pero parece estar desplazada (siempre hacia abajo) , así que empecé a probar con multiplicadores (x1.1, x1.2) para ver cómo resultaba la gráfica y después aplicar la prueba de t.

- Este método dio muy buenos resultados y en las pruebas de t se pudo confirmar que no eran estadísticamente distintos. Para cada contaminante el valor óptimo era distinto y es lo que está marcado en las gráficas (por ejemplo PM25_x1_2). Al hacer esto se ve que incluso los picos tienen el mismo comportamiento y en la prueba de t nos permite decir que, desde una perspectiva estadística, los resultados no son distintos.

- Los resultados nos indican que por desplazamiento, no podemos hablar de concentraciones o calidad del aire, pero sí se puede hablar de la tendencia y, para cada ciudad y cada contaminante, evaluar si hubo un cambio en la pandemia. Esto es en caso de que no consigamos los datos del INECC.

- Los resultados son por día, pero no vale la pena hacer la comparación por día entre un año y otro. Creo que podríamos trabajar con promedios móviles semanales y evaluar el cambio por año y definir si es estadísticamente significativo. Valdría la pena checar en años anteriores (puede ser que se defina que cada año cambia). Y esto se puede reportar con alguna simbología por municipio.

- Para los datos de la Ciudad de México y Guadalajara (están por pasarme los de este año) podemos trabajar con interpolaciones representadas con H3 pero con el mismo método de promedios móviles semanales (ya tengo la ecuación de la interpolación programada en python).

- Faltaría ver el cruce con el tema de movilidad en las ciudades.

- Te adjunto unas visualizaciones que podríamos generar para el tema de riesgo en los municipios, lo vi en el New York Times.

Perdón por el correo super largo. Si tienes chance un día muy temprano para mi (como 6am) lo podemos platicar.

Saludos.
[Image]


________________________________

**Comment by nateraluis** [comment]
jaja no hay problema, es mejor que vaya quedando escrito, es una buena metodología de trabajo que he intentado seguir desde hace tiempo, permite aclarar las ideas y trabajar más fácil de manera remota.

Voy contestando por los puntos:
> -  Voy viendo que la regué con el issue, era el #2  

Suele pasar, podemos seguir trabajando sobre este issue y después lo cerramos junto con el #2 

> - Con ese análisis lo primero que hice fue calcular la mediana para los valores de la calidad del aire de la Ciudad de México (que tenemos por estación y con concentración horaria y por estación) para que solo quedara un valor por día, como está en los datos del Air Quality Index Project (AQIP). 

> - Después tomé los valores de las ciudades mexicanas del AQIP y como los valores venían en índices los convertí a concentraciones. Ahí me di cuenta que los valores no estaban por día, se brincaban algunos (por ejemplo 2 días sí habían datos, 1 no, 1 día sí, 2 no, etc.) 

Estos brincos son iguales para todas las ciudades o son diferentes para cada ciudad? estoy pensando si podemos llenarlos con el promedio del día anterior y el siguiente para tener esos valores. En cualquier caso igual y no es tan relevante si trabajamos con promedios móviles semanales o de 5 días para poder captar los cambios de fin de semana/día laboral.

> - Hice un merge de los datos del AQIP y la CDMX para el mismo periodo y les apliqué una prueba estadística (prueba de t) que analiza si las diferencias entre los valores se pueden explicar por la aleatoriedad de la distribución en los valores o si efectivamente son estadísticamente diferentes. Con esta prueba me salió que todos eran distinos menos PM10. Esas son las gráficas comparativas entre CDMX y AQIP que dicen x1. 
> - Revisando las gráficas se ve que la tendencia es la misma pero parece estar desplazada (siempre hacia abajo) , así que empecé a probar con multiplicadores (x1.1, x1.2) para ver cómo resultaba la gráfica y después aplicar la prueba de t. 
> - Este método dio muy buenos resultados y en las pruebas de t se pudo confirmar que no eran estadísticamente distintos. Para cada contaminante el valor óptimo era distinto y es lo que está marcado en las gráficas (por ejemplo PM25_x1_2). Al hacer esto se ve que incluso los picos tienen el mismo comportamiento y en la prueba de t nos permite decir que, desde una perspectiva estadística, los resultados no son distintos. 
> - Los resultados nos indican que por desplazamiento, no podemos hablar de concentraciones o calidad del aire, pero sí se puede hablar de la tendencia y, para cada ciudad y cada contaminante, evaluar si hubo un cambio en la pandemia. Esto es en caso de que no consigamos los datos del INECC. 

De acuerdo, creo que lo interesante es la tendencia que lleve no necesariamente la comparación de días, sobre todo si queremos seguir midiendo como va cambiando con la reactivación de las diferentes ciudades.  
Lo mismo podemos hacer con los datos de movilidad y de ocupación de diferentes tipos de amenidades de Google, calcular la tendencia e identificar los momentos en los que hay cambios.

> - Los resultados son por día, pero no vale la pena hacer la comparación por día entre un año y otro. Creo que podríamos trabajar con promedios móviles semanales y evaluar el cambio por año y definir si es estadísticamente significativo. Valdría la pena checar en años anteriores (puede ser que se defina que cada año cambia). Y esto se puede reportar con alguna simbología por municipio. 

De acuerdo con los promedios móviles, nos ayuda a comparar mejor y a reducir el ruido de los datos. Hay que ver cuanto tiempo para atrás nos queremos ir, puede ser un año para tener los mismos meses en los datos y comparar por meses. De momento creo que calcular la tendencia y hacer el match con los datos de movilidad es un muy buen primer paso para tener un primer MVP.

> - Para los datos de la Ciudad de México y Guadalajara (están por pasarme los de este año) podemos trabajar con interpolaciones representadas con H3 pero con el mismo método de promedios móviles semanales (ya tengo la ecuación de la interpolación programada en python). 

Perfecto, el algoritmo calcúla las celdas Voronoi y hace el match con los hexágonos? En el código de amenidades tengo una función para rellenar un polígono con los hexágonos de H3.

> - Faltaría ver el cruce con el tema de movilidad en las ciudades. 

Así están los datos reportados por apple (imagen adjunta)
<img width="952" alt="Screen Shot 2020-06-09 at 7 46 55 PM" src="https://user-images.githubusercontent.com/11371711/84182012-05ef5080-aa8a-11ea-875a-653c9c67cf3f.png">

> - Te adjunto unas visualizaciones que podríamos generar para el tema de riesgo en los municipios, lo vi en el New York Times. 
No las pude ver, el correo contestó el issue en GitHub pero no quedaron anexas las visualizaciones :/

> - Perdón por el correo super largo. Si tienes chance un día muy temprano para mi (como 6am) lo podemos platicar.
Va, que día te queda bien?

**Comment by edgaregurrola** [comment]
Siguientes pasos:

- Adjuntar datos de calidad del aire de mayo para la Ciudad de México

**Comment by edgaregurrola** [comment]
Couldn't gather Monterrey's air quality data.
